name: Update S&P500 Chart

on:
  schedule:
    - cron: '0 0 * * *' # 毎日深夜に実行
  workflow_dispatch:      # 手動実行ボタン

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run analysis
        run: python analysis.py
      - name: Commit and Push
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add sp500_latest.png
          git commit -m "Update chart" || exit 0
          git push
